import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="w-full flex justify-center">
      <body className={`${inter.className} wrapper flex flex-col items-center w-full`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
